# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Builds -> skywalking-agent:latest-e2e
ARG BASE_PYTHON_IMAGE

FROM python:${BASE_PYTHON_IMAGE}

VOLUME /services

COPY tests/e2e/base/consumer/* /services/
COPY tests/e2e/base/provider/* /services/

# Copy the project and build
COPY . /skywalking-python/
RUN cd /skywalking-python && apt-get update && apt-get install -y make && make install

# Extra dependencies for e2e services
RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc build-essential\
    && rm -rf /var/lib/apt/lists/* \
    && pip install uwsgi fastapi uvicorn aiohttp flask gunicorn\
    && apt-get purge -y --auto-remove gcc build-essential

# Entrypoint with agent attached
WORKDIR /services

Entrypoint ["sw-python"]
